# Generated by Django 3.2 on 2021-04-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.CharField(auto_created=True, blank=True, db_column='EntryId', max_length=30, primary_key=True, serialize=False, unique=True)),
                ('awbno', models.CharField(blank=True, db_column='AwbNo', max_length=50, null=True)),
                ('refno', models.CharField(blank=True, db_column='RefNo', max_length=50, null=True)),
                ('companycode', models.CharField(blank=True, db_column='CompanyCode', max_length=10, null=True)),
                ('clientcode', models.CharField(blank=True, db_column='ClientCode', max_length=10, null=True)),
                ('couriercode', models.CharField(blank=True, db_column='CourierCode', max_length=10, null=True)),
                ('clientname', models.CharField(blank=True, db_column='ClientName', max_length=100, null=True)),
                ('topay', models.CharField(blank=True, db_column='Topay', max_length=10, null=True)),
                ('cod', models.CharField(blank=True, db_column='COD', max_length=15, null=True)),
                ('riskcoveredby', models.CharField(blank=True, db_column='RiskCoveredBy', max_length=10, null=True)),
                ('recname', models.CharField(blank=True, db_column='RecName', max_length=100, null=True)),
                ('recaddr1', models.CharField(blank=True, db_column='RecAddr1', max_length=100, null=True)),
                ('recaddr2', models.CharField(blank=True, db_column='RecAddr2', max_length=100, null=True)),
                ('recphone', models.CharField(blank=True, db_column='RecPhone', max_length=100, null=True)),
                ('recmail', models.CharField(blank=True, db_column='RecMail', max_length=100, null=True)),
                ('recpin', models.CharField(blank=True, db_column='RecPin', max_length=6, null=True)),
                ('recdestination', models.CharField(blank=True, db_column='RecDestination', max_length=50, null=True)),
                ('recstate', models.CharField(blank=True, db_column='RecState', max_length=2, null=True)),
                ('oda', models.CharField(blank=True, db_column='ODA', max_length=10, null=True)),
                ('ewaybillno', models.CharField(blank=True, db_column='EwayBillNo', max_length=50, null=True)),
                ('invoicevalue', models.CharField(blank=True, db_column='InvoiceValue', max_length=12, null=True)),
                ('invoicenumber', models.CharField(blank=True, db_column='InvoiceNumber', max_length=50, null=True)),
                ('productdesc', models.CharField(blank=True, db_column='ProductDesc', max_length=50, null=True)),
                ('mode', models.CharField(blank=True, db_column='Mode', max_length=10, null=True)),
                ('doctype', models.CharField(blank=True, db_column='DocType', max_length=10, null=True)),
                ('pcs', models.IntegerField(blank=True, db_column='PCS', null=True)),
                ('actweight', models.DecimalField(db_column='ActWeight', decimal_places=2, default=0.0, max_digits=5)),
                ('referenceid', models.CharField(blank=True, db_column='ReferenceId', max_length=50, null=True)),
                ('dimensions', models.CharField(blank=True, db_column='Dimensions', max_length=15, null=True)),
                ('qty', models.IntegerField(blank=True, db_column='Qty', null=True)),
                ('length', models.DecimalField(blank=True, db_column='Length', decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, db_column='Height', decimal_places=2, max_digits=5, null=True)),
                ('width', models.DecimalField(blank=True, db_column='Width', decimal_places=2, max_digits=5, null=True)),
                ('submitteduser', models.CharField(blank=True, db_column='SubmittedUser', max_length=50, null=True)),
                ('recdfrom', models.CharField(blank=True, db_column='RecdFrom', max_length=10, null=True)),
                ('byhub', models.CharField(blank=True, db_column='ByHub', max_length=10, null=True)),
                ('entrytype', models.CharField(blank=True, db_column='EntryType', max_length=10, null=True)),
                ('entrydate', models.DateTimeField(blank=True, db_column='EntryDate', null=True)),
                ('entrytime', models.DateTimeField(blank=True, db_column='EntryTime', null=True)),
                ('entrydatetime', models.DateTimeField(blank=True, db_column='EntryDateTime', null=True)),
                ('enterby', models.CharField(blank=True, db_column='EnterBy', max_length=10, null=True)),
                ('cliname', models.CharField(blank=True, db_column='CliName', max_length=100, null=True)),
                ('cliphone', models.CharField(blank=True, db_column='CliPhone', max_length=100, null=True)),
                ('climail', models.CharField(blank=True, db_column='CliMail', max_length=100, null=True)),
                ('cliadd', models.CharField(blank=True, db_column='CliAdd', max_length=100, null=True)),
                ('clipin', models.CharField(blank=True, db_column='CliPin', max_length=6, null=True)),
            ],
            options={
                'db_table': 'tbBookingWeb',
                'managed': True,
            },
        ),
    ]
