# Generated by Django 2.1.15 on 2021-05-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmcapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_courier',
            field=models.ManyToManyField(related_name='companies', through='rmcapi.CompanyCourierMode', to='rmcapi.Courier'),
        ),
    ]
