# Generated by Django 2.1.15 on 2021-05-17 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmcapi', '0002_auto_20210517_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='company',
            field=models.ForeignKey(db_column='company_code', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rmcapi.Company'),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='userId',
            field=models.ForeignKey(db_column='userid', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='rmcapi.User'),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='user_type',
            field=models.ForeignKey(db_column='user_type_code', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='rmcapi.UserType'),
        ),
    ]
