# Generated by Django 2.1.15 on 2021-05-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmcapi', '0003_auto_20210517_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localsession',
            name='username',
        ),
        migrations.AddField(
            model_name='localsession',
            name='userid',
            field=models.CharField(db_column='userid', default=None, max_length=50, null=True),
        ),
    ]
