# Generated by Django 2.1.15 on 2021-05-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmcapi', '0003_auto_20210530_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbbookingchild',
            name='masterawbno',
            field=models.CharField(db_column='masterawbno_id', max_length=50),
        ),
    ]
