# Generated by Django 2.1.15 on 2021-07-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmcapi', '0005_auto_20210530_1030'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Destination',
        # ),
        # migrations.DeleteModel(
        #     name='PinCode',
        # ),
    ]
