# Generated by Django 2.1.15 on 2021-05-19 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmcapi', '0005_auto_20210519_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycouriermode',
            name='user_type',
            field=models.ForeignKey(db_column='type_code', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='rmcapi.UserType'),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='user_type',
            field=models.ForeignKey(db_column='type_code', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='rmcapi.UserType'),
        ),
    ]
