# Generated by Django 2.1.15 on 2021-07-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmcapi', '0006_auto_20210710_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mtdestination',
            new_name='PinCode',
        ),
    ]
