# Generated by Django 2.1.15 on 2021-07-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmcapi', '0007_auto_20210711_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtpin',
            name='compnay',
            field=models.CharField(db_column='Company', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mtpin',
            name='oda',
            field=models.CharField(db_column='ODA', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mtpin',
            name='pickup',
            field=models.CharField(db_column='PickUp', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mtpin',
            name='topay',
            field=models.CharField(db_column='ToPay', max_length=10, null=True),
        ),
    ]
