# Generated by Django 2.1.15 on 2021-07-16 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmcapi', '0007_auto_20210716_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='PinCode',
        ),
    ]
