# Generated by Django 2.1.15 on 2021-05-19 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmcapi', '0007_auto_20210519_0429'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConsignee',
            fields=[
                ('user_consignee_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(db_column='company_code', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rmcapi.Company')),
            ],
            options={
                'db_table': 'mpUserConsignee',
                'managed': True,
            },
        ),
        migrations.RenameModel(
            old_name='Mtconsignee',
            new_name='Consignee',
        ),
        migrations.AddField(
            model_name='userconsignee',
            name='consignee',
            field=models.ForeignKey(db_column='consignee_code', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rmcapi.Consignee'),
        ),
        migrations.AddField(
            model_name='userconsignee',
            name='user',
            field=models.ForeignKey(db_column='userid', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='rmcapi.User'),
        ),
        migrations.AlterUniqueTogether(
            name='userconsignee',
            unique_together={('user', 'company', 'consignee')},
        ),
    ]
