# Generated by Django 2.1.15 on 2021-07-23 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmcapi', '0009_auto_20210716_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode',
            name='courier',
            field=models.ForeignKey(db_column='CourierCode', max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='rmcapi.Courier'),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='destinationcode',
            field=models.ForeignKey(db_column='DestinationCode', max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='rmcapi.Destination'),
        ),
    ]
