# Generated by Django 2.1.15 on 2021-07-23 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmcapi', '0009_auto_20210716_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('awbno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('declarationdata', models.BinaryField(blank=True, null=True)),
                ('dfilename', models.CharField(blank=True, max_length=80, null=True)),
                ('deextn', models.CharField(blank=True, max_length=10, null=True)),
                ('docketdata', models.BinaryField(blank=True, null=True)),
                ('docketfilename', models.CharField(blank=True, max_length=80, null=True)),
                ('dextn', models.CharField(blank=True, max_length=10, null=True)),
                ('file3data', models.BinaryField(blank=True, null=True)),
                ('file3filename', models.CharField(blank=True, max_length=80, null=True)),
                ('f3extn', models.CharField(blank=True, max_length=10, null=True)),
                ('file4data', models.BinaryField(blank=True, null=True)),
                ('file4filename', models.CharField(blank=True, max_length=80, null=True)),
                ('f4extn', models.CharField(blank=True, max_length=10, null=True)),
                ('file5data', models.BinaryField(blank=True, null=True)),
                ('file5filename', models.CharField(blank=True, max_length=80, null=True)),
                ('f5extn', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'tbAttachments',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='pincode',
            name='courier',
            field=models.ForeignKey(db_column='CourierCode', max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='rmcapi.Courier'),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='destinationcode',
            field=models.ForeignKey(db_column='DestinationCode', max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='rmcapi.Destination'),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='pincode',
            field=models.CharField(db_column='PinCode', default='', max_length=6),
            preserve_default=False,
        ),
    ]
