# Generated by Django 3.2 on 2021-04-27 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custauth', '0002_alter_localsession_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(db_column='UserId', default=uuid.uuid4, max_length=50, primary_key=True, serialize=False),
        ),
    ]
