# Generated by Django 3.2 on 2021-04-27 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custauth', '0004_alter_localsession_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localsession',
            name='connectionid',
            field=models.CharField(default=uuid.uuid4, max_length=30, primary_key=True, serialize=False),
        ),
    ]
