# Generated by Django 3.2 on 2021-04-27 16:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custauth', '0005_alter_localsession_connectionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localsession',
            name='authcreated',
        ),
        migrations.AlterField(
            model_name='localsession',
            name='connectionid',
            field=models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False),
        ),
    ]
