# Generated by Django 3.2 on 2021-04-27 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custauth', '0006_auto_20210427_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localsession',
            old_name='username',
            new_name='userid',
        ),
    ]
