# Generated by Django 3.2 on 2021-04-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custauth', '0007_rename_username_localsession_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='localsession',
            name='authcreated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
