# Generated by Django 3.2 on 2021-04-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custauth', '0008_localsession_authcreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fail_attempt',
            field=models.IntegerField(db_column='fail_attempt', default=0),
        ),
    ]
