# Generated by Django 3.2 on 2021-05-08 07:26

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custauth', '0009_user_fail_attempt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localsession',
            old_name='connectionid',
            new_name='connid',
        ),
        migrations.RenameField(
            model_name='localsession',
            old_name='authcreated',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='localsession',
            old_name='authexp',
            new_name='expirey',
        ),
        migrations.RenameField(
            model_name='localsession',
            old_name='authtoken',
            new_name='token',
        ),
        migrations.AlterField(
            model_name='localsession',
            name='authtype',
            field=models.CharField(db_column='authtype', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='localsession',
            name='connid',
            field=models.CharField(db_column='connectionid', default=uuid.uuid4, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='localsession',
            name='created',
            field=models.DateTimeField(blank=True, db_column='authcreated', null=True),
        ),
        migrations.AlterField(
            model_name='localsession',
            name='expirey',
            field=models.DateTimeField(blank=True, db_column='authexp', null=True),
        ),
        migrations.AlterField(
            model_name='localsession',
            name='token',
            field=models.CharField(db_column='authtoken', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='editdatetime',
            field=models.DateTimeField(blank=True, db_column='EditDateTime', default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='entrydatetime',
            field=models.DateTimeField(blank=True, db_column='EntryDateTime', default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(db_column='is_staff', default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(db_column='is_superuser', default=False),
        ),
    ]
