# Generated by Django 3.2 on 2021-05-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custauth', '0010_auto_20210508_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localsession',
            name='authtype',
            field=models.CharField(db_column='authtype', max_length=50),
        ),
    ]
