# Generated by Django 3.2 on 2021-04-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
