# Generated by Django 3.2 on 2021-04-26 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custauth', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
    ]
