# Generated by Django 3.2 on 2021-04-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custauth', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(auto_created=True, db_column='UserId', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_column='UserPassword', max_length=150),
        ),
    ]
