# Generated by Django 3.2 on 2021-04-26 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custauth', '0004_auto_20210426_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAuth',
            fields=[
                ('connectionid', models.CharField(auto_created=True, db_column='connecionid', max_length=30, primary_key=True, serialize=False)),
                ('authtype', models.CharField(choices=[('authtype_1', 'Session'), ('authtype_2', 'Token'), ('authtype_3', 'Basic')], db_column='authtype', default='authtype_3', max_length=50, unique=True)),
                ('authtoken', models.CharField(db_column='authtoken', max_length=150)),
                ('authexp', models.CharField(blank=True, db_column='authexp', max_length=10, null=True)),
                ('authcreated', models.DateTimeField(blank=True, db_column='authcreated', null=True)),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'custauth_local_session',
                'managed': True,
            },
        ),
    ]
